#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII

bspc config border_width        0
bspc config window_gap		7

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^2'
#bspc rule -a mpv state=floating desktop='^4'
#bspc rule -a code-oss desktop='^3'

nitrogen --restore
exec /home/tlm/.config/polybar/launch.sh
exec picom -f
